### ISSUE TITLE
Installation instructions for Linux - missing chmod +x

### ISSUE THREAD

**Issue by ntavares** [pigeond/gimp-plugin-starnet#1]
Hi @pigeond thanks for sharing this. This has been on my pipeline for years.... today I revisited the subject and found your plugin! Haven't tested yet, but since I've never installed a gimp plugin, it look me a while to figure out why it wasn't showing on the menu (Linux). Installation needs the file to be executable:

chmod u+x <plugin-dir>/plugin-starnet++py

Maybe you want to add that to the installation instructions.

Thank you!

**Comment by pigeond** [comment]
Thanks for this! I'll add that to the instruction.
